unique_ids:
  forms: {Homepage: WJK5BB7XNI77I652OGVLSZTFMG4EZIOM}
  modules: {content_manager: TPIFRIUHX7HVGTYKPP7WGAP5IUXTA6Z5, site_parser: 6FXFRXDVU3UGQNYGZLVQCFDRTJ3SJKW3}
  server_modules: {ServerModule1: KAJ44B3QWT3NWOZTXI4HN4GSAQABO7EJ, site_checker: ZOUIZMZCHZPGQYKCXPZR6O7GUHZKEDID,
    string: I6IE34BGRVAHB4ZDEH73KEFEQTZR6VJD}
  assets: {standard-page.html: B2GICC2UJCPZV2QGDO36N7ND5BU6MVM4, theme.css: HK6DKSBVHZL3ABX3KYOVDTMDMFYYMSCW}
