unique_ids:
  forms: {Homepage: WJK5BB7XNI77I652OGVLSZTFMG4EZIOM}
  modules: {modules: MGFMPOW2SI2O4MUM7M67SJK6SO2D7PHJ, modules.content_manager: TPIFRIUHX7HVGTYKPP7WGAP5IUXTA6Z5,
    modules.site_parser: D5FPYIVJ62BQP6OWVGPJKZ4MMVSKUBEF, modules.string: 5U5ING6WSDO3H7XJ2JJTMZA6E7JLGL27}
  server_modules: {ServerModule1: KAJ44B3QWT3NWOZTXI4HN4GSAQABO7EJ}
  assets: {standard-page.html: B2GICC2UJCPZV2QGDO36N7ND5BU6MVM4, theme.css: HK6DKSBVHZL3ABX3KYOVDTMDMFYYMSCW}
