unique_ids:
  forms:
    Homepage: WJK5BB7XNI77I652OGVLSZTFMG4EZIOM
  modules:
    content_manager: TPIFRIUHX7HVGTYKPP7WGAP5IUXTA6Z5
    site_parser: 6FXFRXDVU3UGQNYGZLVQCFDRTJ3SJKW3
    string: SKHTNKPADCBZADIQYZPYWOLZDMFWD2QR
  server_modules:
    rating_handler: YPNWLT3JAYPHAIP5PNECXVLXAUMBV6IV
    site_checker: ZOUIZMZCHZPGQYKCXPZR6O7GUHZKEDID
  assets:
    standard-page.html: B2GICC2UJCPZV2QGDO36N7ND5BU6MVM4
    theme.css: HK6DKSBVHZL3ABX3KYOVDTMDMFYYMSCW
